Importar base democracia
```{r}
library(htmltab)
LinkWiki="https://es.wikipedia.org/wiki/%C3%8Dndice_de_democracia"
LinkPath='//*[@id="mw-content-text"]/div[1]/table[2]'
democracia=htmltab(LinkWiki,LinkPath)
#Guardar para github
write.csv(democracia,"demosucia.csv", row.names = F)
```
Limpieza
```{r}
democracia[,c(1,9)] = NULL
democracia$País=trimws(democracia$País,whitespace = "[\\h\\v]")
#Pasar a numérica
democracia[,c(2:7)]=lapply(democracia[,c(2:7)],as.numeric)
```
Importar base de países+continentes
```{r}
LinkPath2='//*[@id="mw-content-text"]/div[1]/table[1]'
LinkConti="https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses"
paises=htmltab(LinkConti, LinkPath2)
#Guardar para github
write.csv(paises,"paises_contis_sucia", row.names = F)
```

Limpieza
```{r}
paises[,c(1,3,4,6,7,8)] = NULL
names(paises)=c("País","Continente")
```
Merge paises+continentes
```{r}
democraciafinal=merge(democracia,paises,by.x='País', by.y='País')
#Guardando base final de democracia
write.csv(democracia,"Democraciafinal.csv", row.names = F)
```


Importando variables indepedientes limpias
```{r}
library(rio)
Linkrique="https://raw.githubusercontent.com/Alisson2406/Trabajo-final-de-estadistica/master/Riqueza.csv"
riqueza=import(Linkrique)
Linkurb="https://github.com/fiorelabarbaran/Trabajo/raw/master/urbano.csv"
urban=import(Linkurb)
LinkEduca="https://raw.githubusercontent.com/Giancarlo-Ramirez/Estad-stica-2---Teor-a/master/EducacionFinal.csv"
educa=import(LinkEduca)
```
Merge final
```{r}
datafinal=merge(democracia,educa)
datafinal=merge(datafinal,riqueza)
datafinal=merge(datafinal,urban)
#guardando para github
write.csv(datafinal,"datafinal_E1.csv", row.names = F)
```

